; PlatformIO Project Configuration File
; Board detected as ESP8266 (NodeMCU). AHT10 on D1/D2 → GPIO5/GPIO4

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM8
monitor_port = COM8
